### ISSUE TITLE
제대로 동기화 되지 않는 문제

### ISSUE THREAD

**Issue by FOJF** [naverz/zepeto-multiplay-example#1]
다른 플레이어가 점프를 하며 이동하게 되면 이후의 이동시에 점프하지 않아도 점프를 하면서 이동하게 되거나 위치가 제대로 동기화되지 않는 문제가 존재합니다.
또한 컨텐츠 초반에 몇몇 플레이어는 이동구역을 제한하기 위해서 벽이 존재하는데 이때 벽이 존재하는 플레이어에게는 벽이 없는 플레이어가 벽을 보며 계속 달리는 모션만 취하게 됩니다.

점프 후 위치가 제대로 동기화 되지 않는 문제

https://user-images.githubusercontent.com/61574220/140602963-5fde3ec9-3cfc-4d88-ab01-aef2001789f8.mp4

점프를 한 번만 했지만 멈추지 않고 계속 이동 중이면 계속 점프하며 이동하는 문제

https://user-images.githubusercontent.com/61574220/140602964-d58363a5-6ed6-45da-8662-3d64cb4302b1.mp4

벽을 지나치지 못하고 벽에 계속 부딪히며 달리기만 하는 문제

https://user-images.githubusercontent.com/61574220/140602966-d82524c3-5da2-410f-b73e-26e1185d29c5.mp4

**Comment by cheolhui-lee** [comment]
@hyeonjin-jo 님.
이슈 확인 부탁드립니다.
