### ISSUE TITLE
multiplay에서 파일 데이터 읽는게 가능한가요?

### ISSUE THREAD

**Issue by thkim-nx3games** [naverz/zepeto-multiplay-example#3]
server side에서 table(csv) 데이터를 읽어서 활용하려고 합니다.

가능한지 여부와 간단한 예제 부탁드립니다.

**Comment by hyeonjin-jo** [comment]
안녕하세요
현재는 정책상 파일 i/o에 대한 부분은 막아놓은 상태입니다
내부적으로 논의 중인 부분이라 추후 수정될 수는 있습니다 참고 부탁드립니다
