### ISSUE TITLE
서버와 클라이언트가 코드를 공유해서 써야 할 경우는 어느 폴더에 두어야 하나요?

### ISSUE THREAD

**Issue by thkim-nx3games** [naverz/zepeto-multiplay-example#4]
서버와 클라이언트가 공통된 enum 값과 string 등을 써야 할 경우가 있는데

해당 경우에는 어느 폴더에 두고 작업을 해야 하나요?

**Comment by hyeonjin-jo** [comment]
안녕하세요
서버와 클라이언트는 별도로 구분된 것이라서 각각 필요한 변수들을 선언해서 사용하는 것을 권장드립니다
