### ISSUE TITLE
DataStorage 정상작동 하지 않는 문제

### ISSUE THREAD

**Issue by thkim-nx3games** [naverz/zepeto-multiplay-example#5]
안녕하세요

DataStorage 저장소가 정상작동하지 않는 듯 합니다.

확인 부탁드립니다.

**Comment by thkim-nx3games** [comment]
해당 zepeto-multiplay-example에서는 정상작동하네요

어디가 문제인지 감이 잡히지를 않아서 확인 부탁드립니다.

**Comment by cheolhui-lee** [comment]
안녕하세요.
안되는 상황을 저희가 알기 어려워서 그런데 혹시 자세한 내용 공유를 해주실 수 있을까요?
외부 공유가 어려우시면 담당 해주시는 분을 통해 메일로 전달해주셔도 됩니다.

**Comment by kaav846** [comment]
> 안녕하세요. 안되는 상황을 저희가 알기 어려워서 그런데 혹시 자세한 내용 공유를 해주실 수 있을까요? 외부 공유가 어려우시면 담당 해주시는 분을 통해 메일로 전달해주셔도 됩니다.

새로운 이슈로 등록했습니다. 확인 부탁드리겠습니다.
https://github.com/naverz/zepeto-studio-kor/discussions/112

**Comment by hyeonjin-jo** [comment]
안녕하세요

해당이슈는 https://github.com/naverz/zepeto-studio-kor/discussions/112 에서 완료되어서 close하겠습니다
